In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
sns.set(style='white', palette='muted', color_codes=True)
import matplotlib.pyplot as plt
plt.style.use('ggplot')
import plotly.express as px

In [2]:
df = pd.read_csv(r'C:\Data-Analysis\Covid_Impact\cleaned_covid_sur.csv')

C:\Users\amunv\AppData\Local\Temp\ipykernel_5476\3793751710.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:\Data-Analysis\Covid_Impact\cleaned_covid_sur.csv')

In [3]:
df = df.drop(1)

,Unnamed: 0,cdc_case_earliest_dt,current_status,sex,age_group,race_ethnicity_combined
0,0,2022/01/22,Laboratory-confirmed case,Male,20 - 29 Years,Unknown
1,1,2021/01/24,Laboratory-confirmed case,Male,20 - 29 Years,Unknown
2,2,2021/09/12,Laboratory-confirmed case,Male,20 - 29 Years,Unknown
3,3,2021/04/17,Laboratory-confirmed case,Male,20 - 29 Years,Unknown
4,4,2020/12/04,Laboratory-confirmed case,Male,20 - 29 Years,Unknown
...,...,...,...,...,...,...
82422504,82422580,2021/12/22,Laboratory-confirmed case,Male,20 - 29 Years,Unknown
82422505,82422581,2021/09/08,Laboratory-confirmed case,Male,20 - 29 Years,Unknown
82422506,82422582,2020/11/29,Laboratory-confirmed case,Male,20 - 29 Years,Unknown
82422507,82422583,2021/01/29,Laboratory-confirmed case,Male,20 - 29 Years,Unknown
82422508,82422584,2021/02/11,Laboratory-confirmed case,Male,20 - 29 Years,Unknown